import {InjectionToken, ModuleWithProviders, NgModule} from '@angular/core';
import {NgNavComponent} from './ng-nav.component';
import {FilterPipe} from './utils/FilterPipe';
import {CommonModule} from '@angular/common';
import {MenuItemConfig} from './models/MenuItemConfig';
import {NgNavService} from './ng-nav.service';
import {library} from '@fortawesome/fontawesome-svg-core';
import {
  faAd,
  faAddressBook,
  faAddressCard,
  faAdjust,
  faAirFreshener,
  faAlignCenter,
  faAlignJustify,
  faAlignLeft,
  faAlignRight,
  faAllergies,
  faAmbulance,
  faAmericanSignLanguageInterpreting,
  faAnchor,
  faAngleDoubleDown,
  faAngleDoubleLeft,
  faAngleDoubleRight,
  faAngleDoubleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faAngleUp,
  faAngry,
  faAnkh,
  faAppleAlt,
  faArchive,
  faArchway,
  faArrowAltCircleDown,
  faArrowAltCircleLeft,
  faArrowAltCircleRight,
  faArrowAltCircleUp,
  faArrowCircleDown,
  faArrowCircleLeft,
  faArrowCircleRight,
  faArrowCircleUp,
  faArrowDown,
  faArrowLeft,
  faArrowRight,
  faArrowsAlt,
  faArrowsAltH,
  faArrowsAltV,
  faArrowUp,
  faAssistiveListeningSystems,
  faAsterisk,
  faAt,
  faAtlas,
  faAtom,
  faAudioDescription,
  faAward,
  faBaby,
  faBabyCarriage,
  faBackspace,
  faBackward,
  faBacon,
  faBacteria,
  faBacterium,
  faBahai,
  faBalanceScale,
  faBalanceScaleLeft,
  faBalanceScaleRight,
  faBan,
  faBandAid,
  faBarcode,
  faBars,
  faBaseballBall,
  faBasketballBall,
  faBath,
  faBatteryEmpty,
  faBatteryFull,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryThreeQuarters,
  faBed,
  faBeer,
  faBell,
  faBellSlash,
  faBezierCurve,
  faBible,
  faBicycle,
  faBiking,
  faBinoculars,
  faBiohazard,
  faBirthdayCake,
  faBlender,
  faBlenderPhone,
  faBlind,
  faBlog,
  faBold,
  faBolt,
  faBomb,
  faBone,
  faBong,
  faBook,
  faBookDead,
  faBookmark,
  faBookMedical,
  faBookOpen,
  faBookReader,
  faBorderAll,
  faBorderNone,
  faBorderStyle,
  faBowlingBall,
  faBox,
  faBoxes,
  faBoxOpen,
  faBoxTissue,
  faBraille,
  faBrain,
  faBreadSlice,
  faBriefcase,
  faBriefcaseMedical,
  faBroadcastTower,
  faBroom,
  faBrush,
  faBug,
  faBuilding,
  faBullhorn,
  faBullseye,
  faBurn,
  faBus,
  faBusAlt,
  faBusinessTime,
  faCalculator,
  faCalendar,
  faCalendarAlt,
  faCalendarCheck,
  faCalendarDay,
  faCalendarMinus,
  faCalendarPlus,
  faCalendarTimes,
  faCalendarWeek,
  faCamera,
  faCameraRetro,
  faCampground,
  faCandyCane,
  faCannabis,
  faCapsules,
  faCar,
  faCarAlt,
  faCaravan,
  faCarBattery,
  faCarCrash,
  faCaretDown,
  faCaretLeft,
  faCaretRight,
  faCaretSquareDown,
  faCaretSquareLeft,
  faCaretSquareRight,
  faCaretSquareUp,
  faCaretUp,
  faCarrot,
  faCarSide,
  faCartArrowDown,
  faCartPlus,
  faCashRegister,
  faCat,
  faCertificate,
  faChair,
  faChalkboard,
  faChalkboardTeacher,
  faChargingStation,
  faChartArea,
  faChartBar,
  faChartLine,
  faChartPie,
  faCheck,
  faCheckCircle,
  faCheckDouble,
  faCheckSquare,
  faCheese,
  faChess,
  faChessBishop,
  faChessBoard,
  faChessKing,
  faChessKnight,
  faChessPawn,
  faChessQueen,
  faChessRook,
  faChevronCircleDown,
  faChevronCircleLeft,
  faChevronCircleRight,
  faChevronCircleUp,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faChevronUp,
  faChild,
  faChurch,
  faCircle,
  faCircleNotch,
  faCity,
  faClinicMedical,
  faClipboard,
  faClipboardCheck,
  faClipboardList,
  faClock,
  faClone,
  faClosedCaptioning,
  faCloud,
  faCloudDownloadAlt,
  faCloudMeatball,
  faCloudMoon,
  faCloudMoonRain,
  faCloudRain,
  faCloudShowersHeavy,
  faCloudSun,
  faCloudSunRain,
  faCloudUploadAlt,
  faCocktail,
  faCode,
  faCodeBranch,
  faCoffee,
  faCog,
  faCogs,
  faCoins,
  faColumns,
  faComment,
  faCommentAlt,
  faCommentDollar,
  faCommentDots,
  faCommentMedical,
  faComments,
  faCommentsDollar,
  faCommentSlash,
  faCompactDisc,
  faCompass,
  faCompress,
  faCompressAlt,
  faCompressArrowsAlt,
  faConciergeBell,
  faCookie,
  faCookieBite,
  faCopy,
  faCopyright,
  faCouch,
  faCreditCard,
  faCrop,
  faCropAlt,
  faCross,
  faCrosshairs,
  faCrow,
  faCrown,
  faCrutch,
  faCube,
  faCubes,
  faCut,
  faDatabase,
  faDeaf,
  faDemocrat,
  faDesktop,
  faDharmachakra,
  faDiagnoses,
  faDice,
  faDiceD20,
  faDiceD6,
  faDiceFive,
  faDiceFour,
  faDiceOne,
  faDiceSix,
  faDiceThree,
  faDiceTwo,
  faDigitalTachograph,
  faDirections,
  faDisease,
  faDivide,
  faDizzy,
  faDna,
  faDog,
  faDollarSign,
  faDolly,
  faDollyFlatbed,
  faDonate,
  faDoorClosed,
  faDoorOpen,
  faDotCircle,
  faDove,
  faDownload,
  faDraftingCompass,
  faDragon,
  faDrawPolygon,
  faDrum,
  faDrumSteelpan,
  faDrumstickBite,
  faDumbbell,
  faDumpster,
  faDumpsterFire,
  faDungeon,
  faEdit,
  faEgg,
  faEject,
  faEllipsisH,
  faEllipsisV,
  faEnvelope,
  faEnvelopeOpen,
  faEnvelopeOpenText,
  faEnvelopeSquare,
  faEquals,
  faEraser,
  faEthernet,
  faEuroSign,
  faExchangeAlt,
  faExclamation,
  faExclamationCircle,
  faExclamationTriangle,
  faExpand,
  faExpandAlt,
  faExpandArrowsAlt,
  faExternalLinkAlt,
  faExternalLinkSquareAlt,
  faEye,
  faEyeDropper,
  faEyeSlash,
  faFan,
  faFastBackward,
  faFastForward,
  faFaucet,
  faFax,
  faFeather,
  faFeatherAlt,
  faFemale,
  faFighterJet,
  faFile,
  faFileAlt,
  faFileArchive,
  faFileAudio,
  faFileCode,
  faFileContract,
  faFileCsv,
  faFileDownload,
  faFileExcel,
  faFileExport,
  faFileImage,
  faFileImport,
  faFileInvoice,
  faFileInvoiceDollar,
  faFileMedical,
  faFileMedicalAlt,
  faFilePdf,
  faFilePowerpoint,
  faFilePrescription,
  faFileSignature,
  faFileUpload,
  faFileVideo,
  faFileWord,
  faFill,
  faFillDrip,
  faFilm,
  faFilter,
  faFingerprint,
  faFire,
  faFireAlt,
  faFireExtinguisher,
  faFirstAid,
  faFish,
  faFistRaised,
  faFlag,
  faFlagCheckered,
  faFlagUsa,
  faFlask,
  faFlushed,
  faFolder,
  faFolderMinus,
  faFolderOpen,
  faFolderPlus,
  faFont,
  faFontAwesomeLogoFull,
  faFootballBall,
  faForward,
  faFrog,
  faFrown,
  faFrownOpen,
  faFunnelDollar,
  faFutbol,
  faGamepad,
  faGasPump,
  faGavel,
  faGem,
  faGenderless,
  faGhost,
  faGift,
  faGifts,
  faGlassCheers,
  faGlasses,
  faGlassMartini,
  faGlassMartiniAlt,
  faGlassWhiskey,
  faGlobe,
  faGlobeAfrica,
  faGlobeAmericas,
  faGlobeAsia,
  faGlobeEurope,
  faGolfBall,
  faGopuram,
  faGraduationCap,
  faGreaterThan,
  faGreaterThanEqual,
  faGrimace,
  faGrin,
  faGrinAlt,
  faGrinBeam,
  faGrinBeamSweat,
  faGrinHearts,
  faGrinSquint,
  faGrinSquintTears,
  faGrinStars,
  faGrinTears,
  faGrinTongue,
  faGrinTongueSquint,
  faGrinTongueWink,
  faGrinWink,
  faGripHorizontal,
  faGripLines,
  faGripLinesVertical,
  faGripVertical,
  faGuitar,
  faHamburger,
  faHammer,
  faHamsa,
  faHandHolding,
  faHandHoldingHeart,
  faHandHoldingMedical,
  faHandHoldingUsd,
  faHandHoldingWater,
  faHandLizard,
  faHandMiddleFinger,
  faHandPaper,
  faHandPeace,
  faHandPointDown,
  faHandPointer,
  faHandPointLeft,
  faHandPointRight,
  faHandPointUp,
  faHandRock,
  faHands,
  faHandScissors,
  faHandshake,
  faHandshakeAltSlash,
  faHandshakeSlash,
  faHandsHelping,
  faHandSparkles,
  faHandSpock,
  faHandsWash,
  faHanukiah,
  faHardHat,
  faHashtag,
  faHatCowboy,
  faHatCowboySide,
  faHatWizard,
  faHdd,
  faHeading,
  faHeadphones,
  faHeadphonesAlt,
  faHeadset,
  faHeadSideCough,
  faHeadSideCoughSlash,
  faHeadSideMask,
  faHeadSideVirus,
  faHeart,
  faHeartbeat,
  faHeartBroken,
  faHelicopter,
  faHighlighter,
  faHiking,
  faHippo,
  faHistory,
  faHockeyPuck,
  faHollyBerry,
  faHome,
  faHorse,
  faHorseHead,
  faHospital,
  faHospitalAlt,
  faHospitalSymbol,
  faHospitalUser,
  faHotdog,
  faHotel,
  faHotTub,
  faHourglass,
  faHourglassEnd,
  faHourglassHalf,
  faHourglassStart,
  faHouseDamage,
  faHouseUser,
  faHryvnia,
  faHSquare,
  faIceCream,
  faIcicles,
  faIcons,
  faICursor,
  faIdBadge,
  faIdCard,
  faIdCardAlt,
  faIgloo,
  faImage,
  faImages,
  faInbox,
  faIndent,
  faIndustry,
  faInfinity,
  faInfo,
  faInfoCircle,
  faItalic,
  faJedi,
  faJoint,
  faJournalWhills,
  faKaaba,
  faKey,
  faKeyboard,
  faKhanda,
  faKiss,
  faKissBeam,
  faKissWinkHeart,
  faKiwiBird,
  faLandmark,
  faLanguage,
  faLaptop,
  faLaptopCode,
  faLaptopHouse,
  faLaptopMedical,
  faLaugh,
  faLaughBeam,
  faLaughSquint,
  faLaughWink,
  faLayerGroup,
  faLeaf,
  faLemon,
  faLessThan,
  faLessThanEqual,
  faLevelDownAlt,
  faLevelUpAlt,
  faLifeRing,
  faLightbulb,
  faLink,
  faLiraSign,
  faList,
  faListAlt,
  faListOl,
  faListUl,
  faLocationArrow,
  faLock,
  faLockOpen,
  faLongArrowAltDown,
  faLongArrowAltLeft,
  faLongArrowAltRight,
  faLongArrowAltUp,
  faLowVision,
  faLuggageCart,
  faLungs,
  faLungsVirus,
  faMagic,
  faMagnet,
  faMailBulk,
  faMale,
  faMap,
  faMapMarked,
  faMapMarkedAlt,
  faMapMarker,
  faMapMarkerAlt,
  faMapPin,
  faMapSigns,
  faMarker,
  faMars,
  faMarsDouble,
  faMarsStroke,
  faMarsStrokeH,
  faMarsStrokeV,
  faMask,
  faMedal,
  faMedkit,
  faMeh,
  faMehBlank,
  faMehRollingEyes,
  faMemory,
  faMenorah,
  faMercury,
  faMeteor,
  faMicrochip,
  faMicrophone,
  faMicrophoneAlt,
  faMicrophoneAltSlash,
  faMicrophoneSlash,
  faMicroscope,
  faMinus,
  faMinusCircle,
  faMinusSquare,
  faMitten,
  faMobile,
  faMobileAlt,
  faMoneyBill,
  faMoneyBillAlt,
  faMoneyBillWave,
  faMoneyBillWaveAlt,
  faMoneyCheck,
  faMoneyCheckAlt,
  faMonument,
  faMoon,
  faMortarPestle,
  faMosque,
  faMotorcycle,
  faMountain,
  faMouse,
  faMousePointer,
  faMugHot,
  faMusic,
  faNetworkWired,
  faNeuter,
  faNewspaper,
  faNotEqual,
  faNotesMedical,
  faObjectGroup,
  faObjectUngroup,
  faOilCan,
  faOm,
  faOtter,
  faOutdent,
  faPager,
  faPaintBrush,
  faPaintRoller,
  faPalette,
  faPallet,
  faPaperclip,
  faPaperPlane,
  faParachuteBox,
  faParagraph,
  faParking,
  faPassport,
  faPastafarianism,
  faPaste,
  faPause,
  faPauseCircle,
  faPaw,
  faPeace,
  faPen,
  faPenAlt,
  faPencilAlt,
  faPencilRuler,
  faPenFancy,
  faPenNib,
  faPenSquare,
  faPeopleArrows,
  faPeopleCarry,
  faPepperHot,
  faPercent,
  faPercentage,
  faPersonBooth,
  faPhone,
  faPhoneAlt,
  faPhoneSlash,
  faPhoneSquare,
  faPhoneSquareAlt,
  faPhoneVolume,
  faPhotoVideo,
  faPiggyBank,
  faPills,
  faPizzaSlice,
  faPlaceOfWorship,
  faPlane,
  faPlaneArrival,
  faPlaneDeparture,
  faPlaneSlash,
  faPlay,
  faPlayCircle,
  faPlug,
  faPlus,
  faPlusCircle,
  faPlusSquare,
  faPodcast,
  faPoll,
  faPollH,
  faPoo,
  faPoop,
  faPooStorm,
  faPortrait,
  faPoundSign,
  faPowerOff,
  faPray,
  faPrayingHands,
  faPrescription,
  faPrescriptionBottle,
  faPrescriptionBottleAlt,
  faPrint,
  faProcedures,
  faProjectDiagram,
  faPumpMedical,
  faPumpSoap,
  faPuzzlePiece,
  faQrcode,
  faQuestion,
  faQuestionCircle,
  faQuidditch,
  faQuoteLeft,
  faQuoteRight,
  faQuran,
  faRadiation,
  faRadiationAlt,
  faRainbow,
  faRandom,
  faReceipt,
  faRecordVinyl,
  faRecycle,
  faRedo,
  faRedoAlt,
  faRegistered,
  faRemoveFormat,
  faReply,
  faReplyAll,
  faRepublican,
  faRestroom,
  faRetweet,
  faRibbon,
  faRing,
  faRoad,
  faRobot,
  faRocket,
  faRoute,
  faRss,
  faRssSquare,
  faRubleSign,
  faRuler,
  faRulerCombined,
  faRulerHorizontal,
  faRulerVertical,
  faRunning,
  faRupeeSign,
  faSadCry,
  faSadTear,
  faSatellite,
  faSatelliteDish,
  faSave,
  faSchool,
  faScrewdriver,
  faScroll,
  faSdCard,
  faSearch,
  faSearchDollar,
  faSearchLocation,
  faSearchMinus,
  faSearchPlus,
  faSeedling,
  faServer,
  faShapes,
  faShare,
  faShareAlt,
  faShareAltSquare,
  faShareSquare,
  faShekelSign,
  faShieldAlt,
  faShieldVirus,
  faShip,
  faShippingFast,
  faShoePrints,
  faShoppingBag,
  faShoppingBasket,
  faShoppingCart,
  faShower,
  faShuttleVan,
  faSign,
  faSignal,
  faSignature,
  faSignInAlt,
  faSignLanguage,
  faSignOutAlt,
  faSimCard,
  faSink,
  faSitemap,
  faSkating,
  faSkiing,
  faSkiingNordic,
  faSkull,
  faSkullCrossbones,
  faSlash,
  faSleigh,
  faSlidersH,
  faSmile,
  faSmileBeam,
  faSmileWink,
  faSmog,
  faSmoking,
  faSmokingBan,
  faSms,
  faSnowboarding,
  faSnowflake,
  faSnowman,
  faSnowplow,
  faSoap,
  faSocks,
  faSolarPanel,
  faSort,
  faSortAlphaDown,
  faSortAlphaDownAlt,
  faSortAlphaUp,
  faSortAlphaUpAlt,
  faSortAmountDown,
  faSortAmountDownAlt,
  faSortAmountUp,
  faSortAmountUpAlt,
  faSortDown,
  faSortNumericDown,
  faSortNumericDownAlt,
  faSortNumericUp,
  faSortNumericUpAlt,
  faSortUp,
  faSpa,
  faSpaceShuttle,
  faSpellCheck,
  faSpider,
  faSpinner,
  faSplotch,
  faSprayCan,
  faSquare,
  faSquareFull,
  faSquareRootAlt,
  faStamp,
  faStar,
  faStarAndCrescent,
  faStarHalf,
  faStarHalfAlt,
  faStarOfDavid,
  faStarOfLife,
  faStepBackward,
  faStepForward,
  faStethoscope,
  faStickyNote,
  faStop,
  faStopCircle,
  faStopwatch,
  faStopwatch20,
  faStore,
  faStoreAlt,
  faStoreAltSlash,
  faStoreSlash,
  faStream,
  faStreetView,
  faStrikethrough,
  faStroopwafel,
  faSubscript,
  faSubway,
  faSuitcase,
  faSuitcaseRolling,
  faSun,
  faSuperscript,
  faSurprise,
  faSwatchbook,
  faSwimmer,
  faSwimmingPool,
  faSynagogue,
  faSync,
  faSyncAlt,
  faSyringe,
  faTable,
  faTablet,
  faTabletAlt,
  faTableTennis,
  faTablets,
  faTachometerAlt,
  faTag,
  faTags,
  faTape,
  faTasks,
  faTaxi,
  faTeeth,
  faTeethOpen,
  faTemperatureHigh,
  faTemperatureLow,
  faTenge,
  faTerminal,
  faTextHeight,
  faTextWidth,
  faTh,
  faTheaterMasks,
  faThermometer,
  faThermometerEmpty,
  faThermometerFull,
  faThermometerHalf,
  faThermometerQuarter,
  faThermometerThreeQuarters,
  faThLarge,
  faThList,
  faThumbsDown,
  faThumbsUp,
  faThumbtack,
  faTicketAlt,
  faTimes,
  faTimesCircle,
  faTint,
  faTintSlash,
  faTired,
  faToggleOff,
  faToggleOn,
  faToilet,
  faToiletPaper,
  faToiletPaperSlash,
  faToolbox,
  faTools,
  faTooth,
  faTorah,
  faToriiGate,
  faTractor,
  faTrademark,
  faTrafficLight,
  faTrailer,
  faTrain,
  faTram,
  faTransgender,
  faTransgenderAlt,
  faTrash,
  faTrashAlt,
  faTrashRestore,
  faTrashRestoreAlt,
  faTree,
  faTrophy,
  faTruck,
  faTruckLoading,
  faTruckMonster,
  faTruckMoving,
  faTruckPickup,
  faTshirt,
  faTty,
  faTv,
  faUmbrella,
  faUmbrellaBeach,
  faUnderline,
  faUndo,
  faUndoAlt,
  faUniversalAccess,
  faUniversity,
  faUnlink,
  faUnlock,
  faUnlockAlt,
  faUpload,
  faUser,
  faUserAlt,
  faUserAltSlash,
  faUserAstronaut,
  faUserCheck,
  faUserCircle,
  faUserClock,
  faUserCog,
  faUserEdit,
  faUserFriends,
  faUserGraduate,
  faUserInjured,
  faUserLock,
  faUserMd,
  faUserMinus,
  faUserNinja,
  faUserNurse,
  faUserPlus,
  faUsers,
  faUsersCog,
  faUserSecret,
  faUserShield,
  faUserSlash,
  faUsersSlash,
  faUserTag,
  faUserTie,
  faUserTimes,
  faUtensils,
  faUtensilSpoon,
  faVectorSquare,
  faVenus,
  faVenusDouble,
  faVenusMars,
  faVest,
  faVestPatches,
  faVial,
  faVials,
  faVideo,
  faVideoSlash,
  faVihara,
  faVirus,
  faViruses,
  faVirusSlash,
  faVoicemail,
  faVolleyballBall,
  faVolumeDown,
  faVolumeMute,
  faVolumeOff,
  faVolumeUp,
  faVoteYea,
  faVrCardboard,
  faWalking,
  faWallet,
  faWarehouse,
  faWater,
  faWaveSquare,
  faWeight,
  faWeightHanging,
  faWheelchair,
  faWifi,
  faWind,
  faWindowClose,
  faWindowMaximize,
  faWindowMinimize,
  faWindowRestore,
  faWineBottle,
  faWineGlass,
  faWineGlassAlt,
  faWonSign,
  faWrench,
  faXRay,
  faYenSign,
  faYinYang,
} from '@fortawesome/free-solid-svg-icons';
import {FontAwesomeModule} from '@fortawesome/angular-fontawesome';

export const NgLibConfigService = new InjectionToken<MenuItemConfig>(
  'MenuItemConfig'
);

@NgModule({
  declarations: [NgNavComponent, FilterPipe],
  imports: [
    CommonModule,
    FontAwesomeModule
  ],
  exports: [NgNavComponent]
})
export class NgNavModule {
  constructor() {
    library.add(faAd);
    library.add(faAddressBook);
    library.add(faAddressCard);
    library.add(faAdjust);
    library.add(faAirFreshener);
    library.add(faAlignCenter);
    library.add(faAlignJustify);
    library.add(faAlignLeft);
    library.add(faAlignRight);
    library.add(faAllergies);
    library.add(faAmbulance);
    library.add(faAmericanSignLanguageInterpreting);
    library.add(faAnchor);
    library.add(faAngleDoubleDown);
    library.add(faAngleDoubleLeft);
    library.add(faAngleDoubleRight);
    library.add(faAngleDoubleUp);
    library.add(faAngleDown);
    library.add(faAngleLeft);
    library.add(faAngleRight);
    library.add(faAngleUp);
    library.add(faAngry);
    library.add(faAnkh);
    library.add(faAppleAlt);
    library.add(faArchive);
    library.add(faArchway);
    library.add(faArrowAltCircleDown);
    library.add(faArrowAltCircleLeft);
    library.add(faArrowAltCircleRight);
    library.add(faArrowAltCircleUp);
    library.add(faArrowCircleDown);
    library.add(faArrowCircleLeft);
    library.add(faArrowCircleRight);
    library.add(faArrowCircleUp);
    library.add(faArrowDown);
    library.add(faArrowLeft);
    library.add(faArrowRight);
    library.add(faArrowUp);
    library.add(faArrowsAlt);
    library.add(faArrowsAltH);
    library.add(faArrowsAltV);
    library.add(faAssistiveListeningSystems);
    library.add(faAsterisk);
    library.add(faAt);
    library.add(faAtlas);
    library.add(faAtom);
    library.add(faAudioDescription);
    library.add(faAward);
    library.add(faBaby);
    library.add(faBabyCarriage);
    library.add(faBackspace);
    library.add(faBackward);
    library.add(faBacon);
    library.add(faBacteria);
    library.add(faBacterium);
    library.add(faBahai);
    library.add(faBalanceScale);
    library.add(faBalanceScaleLeft);
    library.add(faBalanceScaleRight);
    library.add(faBan);
    library.add(faBandAid);
    library.add(faBarcode);
    library.add(faBars);
    library.add(faBaseballBall);
    library.add(faBasketballBall);
    library.add(faBath);
    library.add(faBatteryEmpty);
    library.add(faBatteryFull);
    library.add(faBatteryHalf);
    library.add(faBatteryQuarter);
    library.add(faBatteryThreeQuarters);
    library.add(faBed);
    library.add(faBeer);
    library.add(faBell);
    library.add(faBellSlash);
    library.add(faBezierCurve);
    library.add(faBible);
    library.add(faBicycle);
    library.add(faBiking);
    library.add(faBinoculars);
    library.add(faBiohazard);
    library.add(faBirthdayCake);
    library.add(faBlender);
    library.add(faBlenderPhone);
    library.add(faBlind);
    library.add(faBlog);
    library.add(faBold);
    library.add(faBolt);
    library.add(faBomb);
    library.add(faBone);
    library.add(faBong);
    library.add(faBook);
    library.add(faBookDead);
    library.add(faBookMedical);
    library.add(faBookOpen);
    library.add(faBookReader);
    library.add(faBookmark);
    library.add(faBorderAll);
    library.add(faBorderNone);
    library.add(faBorderStyle);
    library.add(faBowlingBall);
    library.add(faBox);
    library.add(faBoxOpen);
    library.add(faBoxTissue);
    library.add(faBoxes);
    library.add(faBraille);
    library.add(faBrain);
    library.add(faBreadSlice);
    library.add(faBriefcase);
    library.add(faBriefcaseMedical);
    library.add(faBroadcastTower);
    library.add(faBroom);
    library.add(faBrush);
    library.add(faBug);
    library.add(faBuilding);
    library.add(faBullhorn);
    library.add(faBullseye);
    library.add(faBurn);
    library.add(faBus);
    library.add(faBusAlt);
    library.add(faBusinessTime);
    library.add(faCalculator);
    library.add(faCalendar);
    library.add(faCalendarAlt);
    library.add(faCalendarCheck);
    library.add(faCalendarDay);
    library.add(faCalendarMinus);
    library.add(faCalendarPlus);
    library.add(faCalendarTimes);
    library.add(faCalendarWeek);
    library.add(faCamera);
    library.add(faCameraRetro);
    library.add(faCampground);
    library.add(faCandyCane);
    library.add(faCannabis);
    library.add(faCapsules);
    library.add(faCar);
    library.add(faCarAlt);
    library.add(faCarBattery);
    library.add(faCarCrash);
    library.add(faCarSide);
    library.add(faCaravan);
    library.add(faCaretDown);
    library.add(faCaretLeft);
    library.add(faCaretRight);
    library.add(faCaretSquareDown);
    library.add(faCaretSquareLeft);
    library.add(faCaretSquareRight);
    library.add(faCaretSquareUp);
    library.add(faCaretUp);
    library.add(faCarrot);
    library.add(faCartArrowDown);
    library.add(faCartPlus);
    library.add(faCashRegister);
    library.add(faCat);
    library.add(faCertificate);
    library.add(faChair);
    library.add(faChalkboard);
    library.add(faChalkboardTeacher);
    library.add(faChargingStation);
    library.add(faChartArea);
    library.add(faChartBar);
    library.add(faChartLine);
    library.add(faChartPie);
    library.add(faCheck);
    library.add(faCheckCircle);
    library.add(faCheckDouble);
    library.add(faCheckSquare);
    library.add(faCheese);
    library.add(faChess);
    library.add(faChessBishop);
    library.add(faChessBoard);
    library.add(faChessKing);
    library.add(faChessKnight);
    library.add(faChessPawn);
    library.add(faChessQueen);
    library.add(faChessRook);
    library.add(faChevronCircleDown);
    library.add(faChevronCircleLeft);
    library.add(faChevronCircleRight);
    library.add(faChevronCircleUp);
    library.add(faChevronDown);
    library.add(faChevronLeft);
    library.add(faChevronRight);
    library.add(faChevronUp);
    library.add(faChild);
    library.add(faChurch);
    library.add(faCircle);
    library.add(faCircleNotch);
    library.add(faCity);
    library.add(faClinicMedical);
    library.add(faClipboard);
    library.add(faClipboardCheck);
    library.add(faClipboardList);
    library.add(faClock);
    library.add(faClone);
    library.add(faClosedCaptioning);
    library.add(faCloud);
    library.add(faCloudDownloadAlt);
    library.add(faCloudMeatball);
    library.add(faCloudMoon);
    library.add(faCloudMoonRain);
    library.add(faCloudRain);
    library.add(faCloudShowersHeavy);
    library.add(faCloudSun);
    library.add(faCloudSunRain);
    library.add(faCloudUploadAlt);
    library.add(faCocktail);
    library.add(faCode);
    library.add(faCodeBranch);
    library.add(faCoffee);
    library.add(faCog);
    library.add(faCogs);
    library.add(faCoins);
    library.add(faColumns);
    library.add(faComment);
    library.add(faCommentAlt);
    library.add(faCommentDollar);
    library.add(faCommentDots);
    library.add(faCommentMedical);
    library.add(faCommentSlash);
    library.add(faComments);
    library.add(faCommentsDollar);
    library.add(faCompactDisc);
    library.add(faCompass);
    library.add(faCompress);
    library.add(faCompressAlt);
    library.add(faCompressArrowsAlt);
    library.add(faConciergeBell);
    library.add(faCookie);
    library.add(faCookieBite);
    library.add(faCopy);
    library.add(faCopyright);
    library.add(faCouch);
    library.add(faCreditCard);
    library.add(faCrop);
    library.add(faCropAlt);
    library.add(faCross);
    library.add(faCrosshairs);
    library.add(faCrow);
    library.add(faCrown);
    library.add(faCrutch);
    library.add(faCube);
    library.add(faCubes);
    library.add(faCut);
    library.add(faDatabase);
    library.add(faDeaf);
    library.add(faDemocrat);
    library.add(faDesktop);
    library.add(faDharmachakra);
    library.add(faDiagnoses);
    library.add(faDice);
    library.add(faDiceD20);
    library.add(faDiceD6);
    library.add(faDiceFive);
    library.add(faDiceFour);
    library.add(faDiceOne);
    library.add(faDiceSix);
    library.add(faDiceThree);
    library.add(faDiceTwo);
    library.add(faDigitalTachograph);
    library.add(faDirections);
    library.add(faDisease);
    library.add(faDivide);
    library.add(faDizzy);
    library.add(faDna);
    library.add(faDog);
    library.add(faDollarSign);
    library.add(faDolly);
    library.add(faDollyFlatbed);
    library.add(faDonate);
    library.add(faDoorClosed);
    library.add(faDoorOpen);
    library.add(faDotCircle);
    library.add(faDove);
    library.add(faDownload);
    library.add(faDraftingCompass);
    library.add(faDragon);
    library.add(faDrawPolygon);
    library.add(faDrum);
    library.add(faDrumSteelpan);
    library.add(faDrumstickBite);
    library.add(faDumbbell);
    library.add(faDumpster);
    library.add(faDumpsterFire);
    library.add(faDungeon);
    library.add(faEdit);
    library.add(faEgg);
    library.add(faEject);
    library.add(faEllipsisH);
    library.add(faEllipsisV);
    library.add(faEnvelope);
    library.add(faEnvelopeOpen);
    library.add(faEnvelopeOpenText);
    library.add(faEnvelopeSquare);
    library.add(faEquals);
    library.add(faEraser);
    library.add(faEthernet);
    library.add(faEuroSign);
    library.add(faExchangeAlt);
    library.add(faExclamation);
    library.add(faExclamationCircle);
    library.add(faExclamationTriangle);
    library.add(faExpand);
    library.add(faExpandAlt);
    library.add(faExpandArrowsAlt);
    library.add(faExternalLinkAlt);
    library.add(faExternalLinkSquareAlt);
    library.add(faEye);
    library.add(faEyeDropper);
    library.add(faEyeSlash);
    library.add(faFan);
    library.add(faFastBackward);
    library.add(faFastForward);
    library.add(faFaucet);
    library.add(faFax);
    library.add(faFeather);
    library.add(faFeatherAlt);
    library.add(faFemale);
    library.add(faFighterJet);
    library.add(faFile);
    library.add(faFileAlt);
    library.add(faFileArchive);
    library.add(faFileAudio);
    library.add(faFileCode);
    library.add(faFileContract);
    library.add(faFileCsv);
    library.add(faFileDownload);
    library.add(faFileExcel);
    library.add(faFileExport);
    library.add(faFileImage);
    library.add(faFileImport);
    library.add(faFileInvoice);
    library.add(faFileInvoiceDollar);
    library.add(faFileMedical);
    library.add(faFileMedicalAlt);
    library.add(faFilePdf);
    library.add(faFilePowerpoint);
    library.add(faFilePrescription);
    library.add(faFileSignature);
    library.add(faFileUpload);
    library.add(faFileVideo);
    library.add(faFileWord);
    library.add(faFill);
    library.add(faFillDrip);
    library.add(faFilm);
    library.add(faFilter);
    library.add(faFingerprint);
    library.add(faFire);
    library.add(faFireAlt);
    library.add(faFireExtinguisher);
    library.add(faFirstAid);
    library.add(faFish);
    library.add(faFistRaised);
    library.add(faFlag);
    library.add(faFlagCheckered);
    library.add(faFlagUsa);
    library.add(faFlask);
    library.add(faFlushed);
    library.add(faFolder);
    library.add(faFolderMinus);
    library.add(faFolderOpen);
    library.add(faFolderPlus);
    library.add(faFont);
    library.add(faFontAwesomeLogoFull);
    library.add(faFootballBall);
    library.add(faForward);
    library.add(faFrog);
    library.add(faFrown);
    library.add(faFrownOpen);
    library.add(faFunnelDollar);
    library.add(faFutbol);
    library.add(faGamepad);
    library.add(faGasPump);
    library.add(faGavel);
    library.add(faGem);
    library.add(faGenderless);
    library.add(faGhost);
    library.add(faGift);
    library.add(faGifts);
    library.add(faGlassCheers);
    library.add(faGlassMartini);
    library.add(faGlassMartiniAlt);
    library.add(faGlassWhiskey);
    library.add(faGlasses);
    library.add(faGlobe);
    library.add(faGlobeAfrica);
    library.add(faGlobeAmericas);
    library.add(faGlobeAsia);
    library.add(faGlobeEurope);
    library.add(faGolfBall);
    library.add(faGopuram);
    library.add(faGraduationCap);
    library.add(faGreaterThan);
    library.add(faGreaterThanEqual);
    library.add(faGrimace);
    library.add(faGrin);
    library.add(faGrinAlt);
    library.add(faGrinBeam);
    library.add(faGrinBeamSweat);
    library.add(faGrinHearts);
    library.add(faGrinSquint);
    library.add(faGrinSquintTears);
    library.add(faGrinStars);
    library.add(faGrinTears);
    library.add(faGrinTongue);
    library.add(faGrinTongueSquint);
    library.add(faGrinTongueWink);
    library.add(faGrinWink);
    library.add(faGripHorizontal);
    library.add(faGripLines);
    library.add(faGripLinesVertical);
    library.add(faGripVertical);
    library.add(faGuitar);
    library.add(faHSquare);
    library.add(faHamburger);
    library.add(faHammer);
    library.add(faHamsa);
    library.add(faHandHolding);
    library.add(faHandHoldingHeart);
    library.add(faHandHoldingMedical);
    library.add(faHandHoldingUsd);
    library.add(faHandHoldingWater);
    library.add(faHandLizard);
    library.add(faHandMiddleFinger);
    library.add(faHandPaper);
    library.add(faHandPeace);
    library.add(faHandPointDown);
    library.add(faHandPointLeft);
    library.add(faHandPointRight);
    library.add(faHandPointUp);
    library.add(faHandPointer);
    library.add(faHandRock);
    library.add(faHandScissors);
    library.add(faHandSparkles);
    library.add(faHandSpock);
    library.add(faHands);
    library.add(faHandsHelping);
    library.add(faHandsWash);
    library.add(faHandshake);
    library.add(faHandshakeAltSlash);
    library.add(faHandshakeSlash);
    library.add(faHanukiah);
    library.add(faHardHat);
    library.add(faHashtag);
    library.add(faHatCowboy);
    library.add(faHatCowboySide);
    library.add(faHatWizard);
    library.add(faHdd);
    library.add(faHeadSideCough);
    library.add(faHeadSideCoughSlash);
    library.add(faHeadSideMask);
    library.add(faHeadSideVirus);
    library.add(faHeading);
    library.add(faHeadphones);
    library.add(faHeadphonesAlt);
    library.add(faHeadset);
    library.add(faHeart);
    library.add(faHeartBroken);
    library.add(faHeartbeat);
    library.add(faHelicopter);
    library.add(faHighlighter);
    library.add(faHiking);
    library.add(faHippo);
    library.add(faHistory);
    library.add(faHockeyPuck);
    library.add(faHollyBerry);
    library.add(faHome);
    library.add(faHorse);
    library.add(faHorseHead);
    library.add(faHospital);
    library.add(faHospitalAlt);
    library.add(faHospitalSymbol);
    library.add(faHospitalUser);
    library.add(faHotTub);
    library.add(faHotdog);
    library.add(faHotel);
    library.add(faHourglass);
    library.add(faHourglassEnd);
    library.add(faHourglassHalf);
    library.add(faHourglassStart);
    library.add(faHouseDamage);
    library.add(faHouseUser);
    library.add(faHryvnia);
    library.add(faICursor);
    library.add(faIceCream);
    library.add(faIcicles);
    library.add(faIcons);
    library.add(faIdBadge);
    library.add(faIdCard);
    library.add(faIdCardAlt);
    library.add(faIgloo);
    library.add(faImage);
    library.add(faImages);
    library.add(faInbox);
    library.add(faIndent);
    library.add(faIndustry);
    library.add(faInfinity);
    library.add(faInfo);
    library.add(faInfoCircle);
    library.add(faItalic);
    library.add(faJedi);
    library.add(faJoint);
    library.add(faJournalWhills);
    library.add(faKaaba);
    library.add(faKey);
    library.add(faKeyboard);
    library.add(faKhanda);
    library.add(faKiss);
    library.add(faKissBeam);
    library.add(faKissWinkHeart);
    library.add(faKiwiBird);
    library.add(faLandmark);
    library.add(faLanguage);
    library.add(faLaptop);
    library.add(faLaptopCode);
    library.add(faLaptopHouse);
    library.add(faLaptopMedical);
    library.add(faLaugh);
    library.add(faLaughBeam);
    library.add(faLaughSquint);
    library.add(faLaughWink);
    library.add(faLayerGroup);
    library.add(faLeaf);
    library.add(faLemon);
    library.add(faLessThan);
    library.add(faLessThanEqual);
    library.add(faLevelDownAlt);
    library.add(faLevelUpAlt);
    library.add(faLifeRing);
    library.add(faLightbulb);
    library.add(faLink);
    library.add(faLiraSign);
    library.add(faList);
    library.add(faListAlt);
    library.add(faListOl);
    library.add(faListUl);
    library.add(faLocationArrow);
    library.add(faLock);
    library.add(faLockOpen);
    library.add(faLongArrowAltDown);
    library.add(faLongArrowAltLeft);
    library.add(faLongArrowAltRight);
    library.add(faLongArrowAltUp);
    library.add(faLowVision);
    library.add(faLuggageCart);
    library.add(faLungs);
    library.add(faLungsVirus);
    library.add(faMagic);
    library.add(faMagnet);
    library.add(faMailBulk);
    library.add(faMale);
    library.add(faMap);
    library.add(faMapMarked);
    library.add(faMapMarkedAlt);
    library.add(faMapMarker);
    library.add(faMapMarkerAlt);
    library.add(faMapPin);
    library.add(faMapSigns);
    library.add(faMarker);
    library.add(faMars);
    library.add(faMarsDouble);
    library.add(faMarsStroke);
    library.add(faMarsStrokeH);
    library.add(faMarsStrokeV);
    library.add(faMask);
    library.add(faMedal);
    library.add(faMedkit);
    library.add(faMeh);
    library.add(faMehBlank);
    library.add(faMehRollingEyes);
    library.add(faMemory);
    library.add(faMenorah);
    library.add(faMercury);
    library.add(faMeteor);
    library.add(faMicrochip);
    library.add(faMicrophone);
    library.add(faMicrophoneAlt);
    library.add(faMicrophoneAltSlash);
    library.add(faMicrophoneSlash);
    library.add(faMicroscope);
    library.add(faMinus);
    library.add(faMinusCircle);
    library.add(faMinusSquare);
    library.add(faMitten);
    library.add(faMobile);
    library.add(faMobileAlt);
    library.add(faMoneyBill);
    library.add(faMoneyBillAlt);
    library.add(faMoneyBillWave);
    library.add(faMoneyBillWaveAlt);
    library.add(faMoneyCheck);
    library.add(faMoneyCheckAlt);
    library.add(faMonument);
    library.add(faMoon);
    library.add(faMortarPestle);
    library.add(faMosque);
    library.add(faMotorcycle);
    library.add(faMountain);
    library.add(faMouse);
    library.add(faMousePointer);
    library.add(faMugHot);
    library.add(faMusic);
    library.add(faNetworkWired);
    library.add(faNeuter);
    library.add(faNewspaper);
    library.add(faNotEqual);
    library.add(faNotesMedical);
    library.add(faObjectGroup);
    library.add(faObjectUngroup);
    library.add(faOilCan);
    library.add(faOm);
    library.add(faOtter);
    library.add(faOutdent);
    library.add(faPager);
    library.add(faPaintBrush);
    library.add(faPaintRoller);
    library.add(faPalette);
    library.add(faPallet);
    library.add(faPaperPlane);
    library.add(faPaperclip);
    library.add(faParachuteBox);
    library.add(faParagraph);
    library.add(faParking);
    library.add(faPassport);
    library.add(faPastafarianism);
    library.add(faPaste);
    library.add(faPause);
    library.add(faPauseCircle);
    library.add(faPaw);
    library.add(faPeace);
    library.add(faPen);
    library.add(faPenAlt);
    library.add(faPenFancy);
    library.add(faPenNib);
    library.add(faPenSquare);
    library.add(faPencilAlt);
    library.add(faPencilRuler);
    library.add(faPeopleArrows);
    library.add(faPeopleCarry);
    library.add(faPepperHot);
    library.add(faPercent);
    library.add(faPercentage);
    library.add(faPersonBooth);
    library.add(faPhone);
    library.add(faPhoneAlt);
    library.add(faPhoneSlash);
    library.add(faPhoneSquare);
    library.add(faPhoneSquareAlt);
    library.add(faPhoneVolume);
    library.add(faPhotoVideo);
    library.add(faPiggyBank);
    library.add(faPills);
    library.add(faPizzaSlice);
    library.add(faPlaceOfWorship);
    library.add(faPlane);
    library.add(faPlaneArrival);
    library.add(faPlaneDeparture);
    library.add(faPlaneSlash);
    library.add(faPlay);
    library.add(faPlayCircle);
    library.add(faPlug);
    library.add(faPlus);
    library.add(faPlusCircle);
    library.add(faPlusSquare);
    library.add(faPodcast);
    library.add(faPoll);
    library.add(faPollH);
    library.add(faPoo);
    library.add(faPooStorm);
    library.add(faPoop);
    library.add(faPortrait);
    library.add(faPoundSign);
    library.add(faPowerOff);
    library.add(faPray);
    library.add(faPrayingHands);
    library.add(faPrescription);
    library.add(faPrescriptionBottle);
    library.add(faPrescriptionBottleAlt);
    library.add(faPrint);
    library.add(faProcedures);
    library.add(faProjectDiagram);
    library.add(faPumpMedical);
    library.add(faPumpSoap);
    library.add(faPuzzlePiece);
    library.add(faQrcode);
    library.add(faQuestion);
    library.add(faQuestionCircle);
    library.add(faQuidditch);
    library.add(faQuoteLeft);
    library.add(faQuoteRight);
    library.add(faQuran);
    library.add(faRadiation);
    library.add(faRadiationAlt);
    library.add(faRainbow);
    library.add(faRandom);
    library.add(faReceipt);
    library.add(faRecordVinyl);
    library.add(faRecycle);
    library.add(faRedo);
    library.add(faRedoAlt);
    library.add(faRegistered);
    library.add(faRemoveFormat);
    library.add(faReply);
    library.add(faReplyAll);
    library.add(faRepublican);
    library.add(faRestroom);
    library.add(faRetweet);
    library.add(faRibbon);
    library.add(faRing);
    library.add(faRoad);
    library.add(faRobot);
    library.add(faRocket);
    library.add(faRoute);
    library.add(faRss);
    library.add(faRssSquare);
    library.add(faRubleSign);
    library.add(faRuler);
    library.add(faRulerCombined);
    library.add(faRulerHorizontal);
    library.add(faRulerVertical);
    library.add(faRunning);
    library.add(faRupeeSign);
    library.add(faSadCry);
    library.add(faSadTear);
    library.add(faSatellite);
    library.add(faSatelliteDish);
    library.add(faSave);
    library.add(faSchool);
    library.add(faScrewdriver);
    library.add(faScroll);
    library.add(faSdCard);
    library.add(faSearch);
    library.add(faSearchDollar);
    library.add(faSearchLocation);
    library.add(faSearchMinus);
    library.add(faSearchPlus);
    library.add(faSeedling);
    library.add(faServer);
    library.add(faShapes);
    library.add(faShare);
    library.add(faShareAlt);
    library.add(faShareAltSquare);
    library.add(faShareSquare);
    library.add(faShekelSign);
    library.add(faShieldAlt);
    library.add(faShieldVirus);
    library.add(faShip);
    library.add(faShippingFast);
    library.add(faShoePrints);
    library.add(faShoppingBag);
    library.add(faShoppingBasket);
    library.add(faShoppingCart);
    library.add(faShower);
    library.add(faShuttleVan);
    library.add(faSign);
    library.add(faSignInAlt);
    library.add(faSignLanguage);
    library.add(faSignOutAlt);
    library.add(faSignal);
    library.add(faSignature);
    library.add(faSimCard);
    library.add(faSink);
    library.add(faSitemap);
    library.add(faSkating);
    library.add(faSkiing);
    library.add(faSkiingNordic);
    library.add(faSkull);
    library.add(faSkullCrossbones);
    library.add(faSlash);
    library.add(faSleigh);
    library.add(faSlidersH);
    library.add(faSmile);
    library.add(faSmileBeam);
    library.add(faSmileWink);
    library.add(faSmog);
    library.add(faSmoking);
    library.add(faSmokingBan);
    library.add(faSms);
    library.add(faSnowboarding);
    library.add(faSnowflake);
    library.add(faSnowman);
    library.add(faSnowplow);
    library.add(faSoap);
    library.add(faSocks);
    library.add(faSolarPanel);
    library.add(faSort);
    library.add(faSortAlphaDown);
    library.add(faSortAlphaDownAlt);
    library.add(faSortAlphaUp);
    library.add(faSortAlphaUpAlt);
    library.add(faSortAmountDown);
    library.add(faSortAmountDownAlt);
    library.add(faSortAmountUp);
    library.add(faSortAmountUpAlt);
    library.add(faSortDown);
    library.add(faSortNumericDown);
    library.add(faSortNumericDownAlt);
    library.add(faSortNumericUp);
    library.add(faSortNumericUpAlt);
    library.add(faSortUp);
    library.add(faSpa);
    library.add(faSpaceShuttle);
    library.add(faSpellCheck);
    library.add(faSpider);
    library.add(faSpinner);
    library.add(faSplotch);
    library.add(faSprayCan);
    library.add(faSquare);
    library.add(faSquareFull);
    library.add(faSquareRootAlt);
    library.add(faStamp);
    library.add(faStar);
    library.add(faStarAndCrescent);
    library.add(faStarHalf);
    library.add(faStarHalfAlt);
    library.add(faStarOfDavid);
    library.add(faStarOfLife);
    library.add(faStepBackward);
    library.add(faStepForward);
    library.add(faStethoscope);
    library.add(faStickyNote);
    library.add(faStop);
    library.add(faStopCircle);
    library.add(faStopwatch);
    library.add(faStopwatch20);
    library.add(faStore);
    library.add(faStoreAlt);
    library.add(faStoreAltSlash);
    library.add(faStoreSlash);
    library.add(faStream);
    library.add(faStreetView);
    library.add(faStrikethrough);
    library.add(faStroopwafel);
    library.add(faSubscript);
    library.add(faSubway);
    library.add(faSuitcase);
    library.add(faSuitcaseRolling);
    library.add(faSun);
    library.add(faSuperscript);
    library.add(faSurprise);
    library.add(faSwatchbook);
    library.add(faSwimmer);
    library.add(faSwimmingPool);
    library.add(faSynagogue);
    library.add(faSync);
    library.add(faSyncAlt);
    library.add(faSyringe);
    library.add(faTable);
    library.add(faTableTennis);
    library.add(faTablet);
    library.add(faTabletAlt);
    library.add(faTablets);
    library.add(faTachometerAlt);
    library.add(faTag);
    library.add(faTags);
    library.add(faTape);
    library.add(faTasks);
    library.add(faTaxi);
    library.add(faTeeth);
    library.add(faTeethOpen);
    library.add(faTemperatureHigh);
    library.add(faTemperatureLow);
    library.add(faTenge);
    library.add(faTerminal);
    library.add(faTextHeight);
    library.add(faTextWidth);
    library.add(faTh);
    library.add(faThLarge);
    library.add(faThList);
    library.add(faTheaterMasks);
    library.add(faThermometer);
    library.add(faThermometerEmpty);
    library.add(faThermometerFull);
    library.add(faThermometerHalf);
    library.add(faThermometerQuarter);
    library.add(faThermometerThreeQuarters);
    library.add(faThumbsDown);
    library.add(faThumbsUp);
    library.add(faThumbtack);
    library.add(faTicketAlt);
    library.add(faTimes);
    library.add(faTimesCircle);
    library.add(faTint);
    library.add(faTintSlash);
    library.add(faTired);
    library.add(faToggleOff);
    library.add(faToggleOn);
    library.add(faToilet);
    library.add(faToiletPaper);
    library.add(faToiletPaperSlash);
    library.add(faToolbox);
    library.add(faTools);
    library.add(faTooth);
    library.add(faTorah);
    library.add(faToriiGate);
    library.add(faTractor);
    library.add(faTrademark);
    library.add(faTrafficLight);
    library.add(faTrailer);
    library.add(faTrain);
    library.add(faTram);
    library.add(faTransgender);
    library.add(faTransgenderAlt);
    library.add(faTrash);
    library.add(faTrashAlt);
    library.add(faTrashRestore);
    library.add(faTrashRestoreAlt);
    library.add(faTree);
    library.add(faTrophy);
    library.add(faTruck);
    library.add(faTruckLoading);
    library.add(faTruckMonster);
    library.add(faTruckMoving);
    library.add(faTruckPickup);
    library.add(faTshirt);
    library.add(faTty);
    library.add(faTv);
    library.add(faUmbrella);
    library.add(faUmbrellaBeach);
    library.add(faUnderline);
    library.add(faUndo);
    library.add(faUndoAlt);
    library.add(faUniversalAccess);
    library.add(faUniversity);
    library.add(faUnlink);
    library.add(faUnlock);
    library.add(faUnlockAlt);
    library.add(faUpload);
    library.add(faUser);
    library.add(faUserAlt);
    library.add(faUserAltSlash);
    library.add(faUserAstronaut);
    library.add(faUserCheck);
    library.add(faUserCircle);
    library.add(faUserClock);
    library.add(faUserCog);
    library.add(faUserEdit);
    library.add(faUserFriends);
    library.add(faUserGraduate);
    library.add(faUserInjured);
    library.add(faUserLock);
    library.add(faUserMd);
    library.add(faUserMinus);
    library.add(faUserNinja);
    library.add(faUserNurse);
    library.add(faUserPlus);
    library.add(faUserSecret);
    library.add(faUserShield);
    library.add(faUserSlash);
    library.add(faUserTag);
    library.add(faUserTie);
    library.add(faUserTimes);
    library.add(faUsers);
    library.add(faUsersCog);
    library.add(faUsersSlash);
    library.add(faUtensilSpoon);
    library.add(faUtensils);
    library.add(faVectorSquare);
    library.add(faVenus);
    library.add(faVenusDouble);
    library.add(faVenusMars);
    library.add(faVest);
    library.add(faVestPatches);
    library.add(faVial);
    library.add(faVials);
    library.add(faVideo);
    library.add(faVideoSlash);
    library.add(faVihara);
    library.add(faVirus);
    library.add(faVirusSlash);
    library.add(faViruses);
    library.add(faVoicemail);
    library.add(faVolleyballBall);
    library.add(faVolumeDown);
    library.add(faVolumeMute);
    library.add(faVolumeOff);
    library.add(faVolumeUp);
    library.add(faVoteYea);
    library.add(faVrCardboard);
    library.add(faWalking);
    library.add(faWallet);
    library.add(faWarehouse);
    library.add(faWater);
    library.add(faWaveSquare);
    library.add(faWeight);
    library.add(faWeightHanging);
    library.add(faWheelchair);
    library.add(faWifi);
    library.add(faWind);
    library.add(faWindowClose);
    library.add(faWindowMaximize);
    library.add(faWindowMinimize);
    library.add(faWindowRestore);
    library.add(faWineBottle);
    library.add(faWineGlass);
    library.add(faWineGlassAlt);
    library.add(faWonSign);
    library.add(faWrench);
    library.add(faXRay);
    library.add(faYenSign);
    library.add(faYinYang);



  }

  static forRoot(config: MenuItemConfig[]): ModuleWithProviders {
    return {
      ngModule: NgNavModule,
      providers: [
        NgNavService,
        {
          provide: NgLibConfigService,
          useValue: config
        }
      ]
    };
  }
}
